### ISSUE TITLE
TypeObject.prototype._readBytes zero byteLength, but read all bytes

### ISSUE THREAD

**Issue by playertwo** [enricostara/telegram-tl-node#1]
in file /lib/type-object.js 
TypeObject.prototype._readBytes
When byteLength = 0 function work incorrectly

**Comment by enricostara** [comment]
Why you should read 0 bytes? Function takes 0 like undefined (not significant) and reads all the buffer.

**Comment by playertwo** [comment]
I try to call getConfig, there are empty string in Config.hostname

**Comment by enricostara** [comment]
You mean https://core.telegram.org/type/DcOption dcOption.hostname? 

Ok, I didn't yet test this case! if a string is empty and declares 0 bytes-length I have to change the code :)
Thanks, I'll change it asap

**Comment by playertwo** [comment]
Yes. 
Thank you for great work :)

**Comment by enricostara** [comment]
Thanks that you help me to test the code ;)

**Comment by enricostara** [comment]
I fixed the problem, you can also find a new integration test in [telegram-MT-node](https://github.com/enricostara/telegram-mt-node/tree/master/test/integration) where the 'getConfig' call is up and running, let me know
